# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of os and other tools you might need
# Using mambaforge solves excessive memory use issues
build:
  os: "ubuntu-24.04"
  tools:
    python: "mambaforge-latest"
  jobs:
    pre_install:
      - mkdir --parents docs/_static/conda_envs
      - cp ci/envs/*.yml docs/_static/conda_envs/
    post_install:
      - mamba list

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF
formats: []

# Specify conda env required to build docs 
conda:
  environment: ci/envs/readthedocs.yml
