# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of os and other tools you might need
# Using mambaforge solves excessive memory use issues
build:
  os: "ubuntu-24.04"
  tools:
    python: "mambaforge-latest"
  jobs:
    post_install:
      - mamba list
      #- find / -name "mod_spatialite.so"
      #- . /home/docs/.asdf/installs/python/mambaforge-23.11.0-0/etc/profile.d/conda.sh
      #- /home/docs/.asdf/installs/python/miniconda3-3.12-24.9.2-0/etc/profile.d/conda.sh
      #- /home/docs/.asdf/installs/python/miniconda3-3.12-24.9.2-0/bin/activate orthosegdoc
      #- . etc/profile.d/conda.sh
      #- cat ~/.conda/environments.txt
      #- ls -al ~/checkouts/readthedocs.org/user_builds/orthoseg/conda/259
      #- ls -al ~/checkouts/readthedocs.org/user_builds/orthoseg/conda/259/bin
      #- PATH="$PATH:/home/docs/checkouts/readthedocs.org/user_builds/orthoseg/conda/259/lib"
      #- echo $PATH
      #- export PATH="/home/docs/checkouts/readthedocs.org/user_builds/orthoseg/conda/259/lib:$PATH"
      # - conda activate 259


# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF
formats: []

# Specify conda env required to build docs 
conda:
  environment: ci/envs/readthedocs.yml
