# This is the standard environment with recent version of all dependencies.
name: orthoseg
channels:
  - conda-forge
dependencies:
  - python <3.13
  - pip
  # required
  - gdal
  - gdown
  - geofileops >=0.9
  - geopandas-base >=1.0
  - matplotlib-base
  - numpy
  - owslib
  - pillow
  - pycron
  - pygeoops >=0.4
  - pyproj
  - rasterio
  - shapely >=2
  - simplification
  # From tf 2.16, keras 3 is installed which is not supported by orthoseg 0.6
  - tensorflow-cpu >=2.8,<2.16
  # testing
  - pytest
  - pytest-cov
  - pytest-order
  - pip:
    - segmentation-models >=1.0
    - orthoseg >=0.6