# This config file contains the specific settings for this orthoseg project.
#
# The config used for an orthoseg project is loaded in the following order:
#   1) the project defaults as "hardcoded" in orthoseg (project_defaults.ini)
#   2) any .ini files specified in the general.extra_config_files_to_load 
#      parameter (in this file).
#   3) this config file
# Parameters specified in a config file loaded later in the order above
# overrule the corresponding parameter values specified in a previously 
# loaded config file.

[general]
# Extra config files to load for this project. They will be loaded in the 
# order specified and can be specified one path per line, comma seperated.
# If a relative path is used it will be resolved towards the parent dir of 
# this file.
extra_config_files_to_load = ../project_defaults_overrule.ini

# The subject that will be segmented.
segment_subject = sportsfields

# Settings regarding the download action.
[download]

# Schedule to control when images can be downloaded.
#
# If not specified there is no time limitation.
cron_schedule

# Settings for the neural network model you want to use.
[model]

# The segmentation model architecture to use. 
#
# The default is inceptionresnetv2+unet, but as this is just a sample project,
# use a light-weight architecture to speed up training/inference.
architecture = mobilenetv2+linknet

# Settings concerning the train process.
[train]

# The minimum accuracy to save the model.
# Lower the default of 0.8 as this model doesn't always get to that accuracy.
save_min_accuracy = 0.75

# Parameters regarding the size/resolution of the images used to train on.
image_pixel_width = 256
image_pixel_height = 256
image_pixel_x_size = 0.5
image_pixel_y_size = 0.5

# The classes to use for this segmentation
classes =   {   "background": {
                    "labelnames": ["ignore_for_training", "background", "swimming_pool"],
                    "weight": 1
                },
                "hockey_field": {
                    "labelnames": ["hockey_field"],
                    "weight": 1
                },
                "football_field": {
                    "labelnames": ["football_field"],
                    "weight": 1
                },
                "tennis_padel_area": {
                    "labelnames": ["padel_court", "padel_area", "tennis_court", "tennis_area"],
                    "weight": 1
                }
            }

# Settings concerning the prediction process.
[predict]

# Info about the source images that need to be segmented.
# The image_layer must be specified to be able to predict.
image_layer = BEFL-2025-sportsfields

# The batch size to use. 
# Depends on available hardware, model used and image size.
batch_size = 1

# Parameters regarding the size/resolution of the images to run predict on.
#
# For some model architectures there are limitations on the image sizes
# supported. E.g. if you use the linknet decoder, the images pixel width and height
# has to be divisible by factor 32.
image_pixel_width = 512
image_pixel_height = 512
image_pixel_x_size = 0.5
image_pixel_y_size = 0.5
image_pixels_overlap = 64
