# In this file, the image layers we can use are configured. 

# WMS layer with RGB images of 2025 with a roi of the Flemish region in Belgium.
[BEFL-2025]

# WMS information of the layer
wms_server_url = https://geo.api.vlaanderen.be/omw/wms?
wms_layernames = OMWRGB25VL
wms_layerstyles = default
wms_version = 1.3.0
projection = epsg:31370

# Path to a file with the ROI to use when predicting
roi_filepath = ./_rois/refgew_vlaanderen+brussel.gpkg.zip

# WMS layer with RGB images of 2024 with a roi of the Flemish region in Belgium.
[BEFL-2024]

# WMS information of the layer
wms_server_url = https://geo.api.vlaanderen.be/omw/wms?
wms_layernames = OMWRGB24VL
wms_layerstyles = default
wms_version = 1.3.0
projection = epsg:31370

# Path to a file with the ROI to use when predicting
roi_filepath = ./_rois/refgew_vlaanderen+brussel.gpkg.zip

# WMS layer with RGB images of 2023 with a roi of the Flemish region in Belgium.
[BEFL-2023]

# WMS information of the layer
wms_server_url = https://geo.api.vlaanderen.be/omw/wms?
wms_layernames = OMWRGB23VL
wms_layerstyles = default
wms_version = 1.3.0
projection = epsg:31370

# Path to a file with the ROI to use when predicting
roi_filepath = ./_rois/refgew_vlaanderen+brussel.gpkg.zip

# WMS layer with RGB images of 2019 with a roi of the Flemish region in Belgium.
[BEFL-2019]

# WMS information of the layer
wms_server_url = https://geo.api.vlaanderen.be/omw/wms?
wms_layernames = OMWRGB19VL
wms_layerstyles = default
wms_version = 1.3.0
projection = epsg:31370

# Path to a file with the ROI to use when predicting
roi_filepath = ./_rois/refgew_vlaanderen+brussel.gpkg.zip

# WMS layer with RGB images of 2025 with a bounding box where sportsfields are located.
[BEFL-2025-sportsfields]

# WMS information of the layer
wms_server_url = https://geo.api.vlaanderen.be/omw/wms?
wms_layernames = OMWRGB25VL
wms_layerstyles = default
wms_version = 1.3.0
projection = epsg:31370

# Bbox of the ROI to use when predicting
bbox = 154010, 204350, 154250, 204650

# When use_cache is set to ifavailable, the cache will be used if it exists, but if it
# does not exist, the images will be downloaded on the fly.
use_cache = ifavailable

# WMTS layer with 2025 RGB images with a bounding box where a football field is located.
[BEFL-2025-footballfield-WMTS]
    
# WMTS information of the layer
wmts_server_url = https://geo.api.vlaanderen.be/omw/wmts?
wmts_layernames = omwrgb25vl
wmts_layerstyles = default
wmts_version = 1.0.0
wmts_tile_matrix_set = BPL72VL

projection = epsg:31370
layername = BEFL-2025-footballfield-WMTS

# Specify the format the images are requested and saved in. Defaults to image/jpeg.
image_format = image/jpeg

# Bbox of the ROI to use when predicting
bbox = 174900, 176400, 175300, 176600

# XYZ layer with OSM images with a bbox where a football field is located.
[OSM-XYZ-footballfield]

# The GDAL WMS driver can be used to use several types of services. An .xml file is used
# to configure the layer. This layer is an example showing how to configure an XYZ tile
# service. More information can be found here: https://gdal.org/drivers/raster/wms.html
path = ./imagelayer_osm.xml
layername = OSM-XYZ-footballfield
projection = epsg:3857

# Specify the format the images are requested and saved in. Defaults to image/jpeg.
image_format = image/jpeg

# Bbox of the ROI to use when predicting
bbox = 525500, 6603100, 525600, 6603200

# Local sentinel 2 image and a bbox where an agricultural field is located.
[BEFL-TEST-s2-2023-fields]

path = ./fields/input_raster/BEFL-TEST-s2_2023-05-01_2023-07-01_B08-B04-B03_min_byte.tif
projection = epsg:32631
layername = BEFL-TEST-s2-2023-fields
# Specify the format the images are requested and saved in. Defaults to image/jpeg.
image_format = image/png

# Bbox of the ROI to use when predicting
bbox = 174900, 176200, 175300, 176700

# When set to ifavailable, the cache will be used if it exists, but if it does
# not exist, the image will be downloaded.
use_cache = no
